### PR TITLE
chore: refactor

### PR DESCRIPTION
**Pull request by leomotors**
- Format files & Rules
- Bump packages to latest
- ~~Next.js App Dir~~

### CODE REVIEW

**Comment by shalluv** [comment]
Why appDir?😭 
IMO, this project's deadlines are very close. Although, the App Router has been announced as stable, we can't take any risks atm. 
What do you think?

**Comment by betich** [comment]
not sure if we are ready for app dir hahaha

**Comment by betich** [comment]
cc @boomchanotai

**Comment by boomchanotai** [comment]
fuck no app dir

**Review by shalluv — APPROVED** [review]
Well done!

**Pull request merged**
