### PR TITLE
Fix/lint end of line

### PR DESCRIPTION
**Pull request by shalluv**
- End-of-line errors occur because DOS and UNIX files end in different ways.
- Remove the unused rocket smoke image.

### CODE REVIEW

**Comment by leomotors** [comment]
If someone ends up using CRLF. Should prettier already convert it to LF at the pre-commit hook?

**Comment by shalluv** [comment]
Yes, prettier changed it. Then, it's error on my Window.55555555555555😭😭😭😭

**Review by leomotors — APPROVED** [review]
approve because we are speedrunning this web.

good luck everyone orz

**Comment by shalluv** [comment]
Should be fine! May be force be with us✊✊✊

**Pull request merged**
